name: "Docker Build"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ArchLinux:
    runs-on: "ubuntu-latest"
    container:
      image: "archlinux:base-devel"
    steps:
      - name: "Create an user"
        run: "useradd -m user"
      - uses: "actions/checkout@v3"
      - name: "Chown files"
        run: "chown -R user:user ."
      - name: "Install build dependencies"
        run: "pacman --noconfirm -Syu && pacman --noconfirm -S cmake obs-studio opencv"
      - name: "Make the package"
        working-directory: "scripts"
        run: "sudo -u user -- makepkg"

  UbuntuArm64:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
      - uses: "actions/checkout@v3"
      - run: |
          docker run -t\
            --mount "type=bind,source=${{ github.workspace }},target=/workspace" \
            ubuntu:jammy \
            sh -c "cd /workspace &&
              apt-get update &&
              apt-get install -y sudo zsh &&
              CI=1 ./.github/scripts/build-linux.sh &&
              CI=1 ./.github/scripts/package-linux.sh
            "
